# Numpy

Numpy es una de las librerías más importantes del stack científico de Python. Provee objectos del tipo `array` multidimensionales y de alta performance.

Para usar Numpy, se necesita importar el paquete `numpy`:

In [ ]:
# ! pip install numpy

In [ ]:
import numpy as np

## Arrays

Un array de Numpy es una estructura de datos del mismo tipo indexados por una tupla de enteros no negativos. 

* `n dimensions`: rank del array
* `size`: tupla de enteros que indica el tamaño en cada dimensión

Se puede crear un numpy array a partir de una lista de elementos:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])                

In [ ]:
a[0] = 5                 # Change an element of the array
print(a)  

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

Numpy provee varias funciones para crear arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

### Array indexing

Hay varias formas de indexar arrays con Numpy:

### Slicing

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

Al hacer slicing se obtiene *una vista* del array y, al modificarla, se modifica también el array

In [ ]:
print(a[0, 1])

In [ ]:
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

### Integer array indexing

Aplicando slicing se obtiene una vista del array, o un sub array.
Con integer array indexing se pueden construir arrays arbitrarios a partir de uno dado:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

In [ ]:
# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

Un array se puede emplear también para referenciar los elementos en los índices que éste contenga:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])
print(b)

In [ ]:
print(np.arange(4))

In [ ]:
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

### Boolean array indexing

Permite "filtrar" los elementos de un array que cumplan una condicion determinada:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

In [ ]:

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

In [ ]:
# We can do all of the above in a single concise statement:
print(a[a > 2])

## Datatypes

Los objetos dentro de un array deben ser del mismo tipo. Numpy va a tratar de adivinar de qué tipo son los elementos al momento de crearlos o se puede especificar explícitamente el tipo con el parámetro `dtype`:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

### Array math

Numpy permite realizar operaciones matemáticas elementales entre arrays, elemento a elemento, tanto con los operadores bien conocidos, como con métodos de numpy:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [ ]:
print(x)
print(y)

In [ ]:
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Nótese que  `*` se refiere a *multiplicación elemento a elemento* y no producto matricial.  
Para productos matriciales (o vectoriales) se emplea el método `dot`:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print(y)

In [ ]:
v = np.array([9,10])
w = np.array([11, 12])

print(v)
print(w)

In [ ]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

Además existe el operador `@` que hace referencia a `dot`.

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Es preciso aprovechar la performance de los métodos que ofrece numpy, como `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

Más [métodos](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

**Transponer** una matriz puede ser necesario para manipular arrays multidimensionales:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

### Broadcasting

Broadcasting es un poderoso mecanismo que permite realizar operaciones entre arrays de diferentes shapes:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

print(x)
print(v)
print(y)

Camino largo:

In [ ]:

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

Camino corto (Numpy):

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

Algunas aplicaciones de broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
print(v)
print(w)

In [ ]:
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

## Ejercicios Numpy

### Sincrónicos

* Crear dos arrays de igual dimensión y computar la suma entre los mismos.

* Crear una matriz de 3x3 y obtener el producto de la misma con un escalar.

### Asincrónicos

* Crear una matriz identidad de 4x4.

* Crear un array con los números del 0 al 26 inclusive y redimensionarlo para lograr una matríz de 3x3.

* Crear una matriz de 3x3 con valores arbitrarios y obtener el array booleano con `True` para valores pares.

> Más info [numpy official](https://numpy.org/)